version: "3.5"

services:
  lightning-challenge:
    image: lightning-challenge
    environment:
      - DATABASE_URL=postgres://postgres:postgres@127.0.0.1/postgres
      - DB_INITIAL_POOL_SIZE=20
      - DB_MAX_POOL_SIZE=100
      - API_USE_DB_FUNC=true
      - PORT=3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./migrations/20240304235544_create_transactions_table.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"